### ISSUE TITLE
Crashes Server-Side, Invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by MadSciSlack** [NyanMC/ChromaticArsenal#4]
Hello!  The latest version of Chromatic Arsenal (1.17.0) crashes server-side.  I've posted the relevant crash log contents below, hopefully this helps.  Let me know if you need anything else, I'll check back later and will help to the best of my ability.

It seemed to work okay in single player, which is not surprising based on the log below. 

Cheers,

Slack.
[crash-2024-02-28_23.01.24-fml.txt](https://github.com/NyanMC/ChromaticArsenal/files/14440822/crash-2024-02-28_23.01.24-fml.txt)

**Comment by MadSciSlack** [comment]
Just a quick update: Rolling back to the previous version of Chromatic Arsenal does allow the server to launch.

**Comment by NyanMC** [comment]
not again. the one time i forget to try running on the server first before publishing the mod

**Comment by NyanMC** [comment]
on a more serious note, i think i know what the problem is. if i'm right the fix won't take too long

**Comment by NyanMC** [comment]
did not mean to close that so soon but that commit should fix the issue, working on releasing it to curseforge and modrinth right now

**Comment by NyanMC** [comment]
1.17.1 has just been released on modrinth which should fix this issue, it's still processing on curseforge. reopen if the issue persists

**Comment by MadSciSlack** [comment]
Lmao, gotta test! 
I'm not too worried, you'll get this sorted.  Rolling back to 1.16.x got us back up for the meantime, and my pack isn't public yet anyway.

**Comment by MadSciSlack** [comment]
I'm doing a round of updates for my pack, so I'll be testing out the new version.  Unless something goes wrong, no news is good news.  Thanks for fixing this up quickly.
